const ACTION_TYPES = {
  LOGIN_USER: "LOGIN_USER",
  REGISTER_USER: "REGISTER_USER",
  GET_FOOD_DETAILS_NUTRITION: "GET_FOOD_DETAILS_NUTRITION",
  GET_FOOD_LIST_NUTRITION: "GET_FOOD_LIST_NUTRITION",
  CLEAR_FOOD_TPYE: "CLEAR_FOOD_TPYE",
  CLEAR_AUTH: "CLEAR_AUTH",
  GET_PROFILE_DEATIL: "GET_PROFILE_DETAIL",
  UPDATE_PROFILE_DEATIL: "UPDATE_PROFILE_DEATIL",
  CLEAR_GET_PROFILE: "CLEAR_GET_PROFILE",

  UPDATE_SERVING_VALUE: "UPDATE_SERVING_VALUE",
  SAVE_NUTRITION_FOOD: "SAVE_NUTRITION_FOOD",
  GET_RECOMMED_CAL: "GET_RECOMMED_CAL",
  GET_FOOD_BY_DATE: "GET_FOOD_BY_DATE",
  GET_FOOD_FREQUENT: "GET_FOOD_FREQUENT",
  GET_FOOD_RECENT: "GET_FOOD_RECENT",
  DELETE_FOOD: "DELETE_FOOD",

  LOADER: "LOADER",
  ERROR: "ERROR",
  ERROR_CLEAR: "ERROR_CLEAR",

  CLEAR_FOOD_RES: "CLEAR_FOOD_RES",
  ADD_BASE_TARGET: "ADD_BASE_TARGET",

  GET_REPORTS: "GET_REPORTS",
  GET_REPORTS_OVERVIEW: "GET_REPORTS_OVERVIEW",
  GET_GRAPH_BY_PAGE: "GET_GRAPH_BY_PAGE",

  CLEAR_GRAPH_BY_PAGE: "CLEAR_GRAPH_BY_PAGE",
  CLEAR_WATER: "CLEAR_WATER",
  UPDATE_WATER: "UPDATE_WATER",
  GET_WATER: "GET_WATER",
  GET_CIRCULATORY_REPORT: "GET_CIRCULATORY_REPORT",
};

export default ACTION_TYPES;
