const API_CONST = {
  N_LOGIN_USER: "N_LOGIN_USER",
  N_REGISTER_USER: "N_REGISTER_USER",
  N_GET_FOOD_DETAILS_NUTRITION: "N_GET_FOOD_DETAILS_NUTRITION",
  N_GET_FOOD_LIST_NUTRITION: "N_GET_FOOD_LIST_NUTRITION",
  N_GET_PROFILE_DETAILS: "N_GET_PROFILE_DETAILS",
  N_UPDATE_PROFILE_DETAILS: "N_UPDATE_PROFILE_DETAILS",
  N_UPLOAD_IMAGE: "N_UPLOAD_IMAGE",
  N_CLEAR_PROFILE: "N_CLEAR_PROFILE",
  N_GET_RECOMMEDE_CAL: "N_GET_RECOMMEDE_CAL",
  N_GET_FOOD_BY_DATE: "N_GET_FOOD_BY_DATE",
  N_GET_FOOD_RECENT: "N_GET_FOOD_RECENT",
  N_GET_FOOD_FREQUENT: "N_GET_FOOD_FREQUENT",
  N_SAVE_NUTRITION_FOOD_DETAILS: "N_SAVE_NUTRITION_FOOD_DETAILS",
  N_DELETE_FOOD: "N_DELETE_FOOD",
  N_ADD_BASE_TARGET: "N_ADD_BASE_TARGET",
  N_REPORTS: "N_REPORTS",
  N_REPORTS_OVERVIEW: "N_REPORTS_OVERVIEW",
  N_GRAPH_BY_PAGE: "N_GRAPH_BY_PAGE",

  N_LOADER: "N_LOADER",
  N_ERROR: "N_ERROR",
  N_ERROR_CLEAR: "N_ERROR_CLEAR",

  N_UPDATE_WATER: "N_UPDATE_WATER",
  N_GET_WATER: "N_GET_WATER",
  N_CIRCULATORY_REPORT: "N_CIRCULATORY_REPORT",
};
export default API_CONST;
